# kubectl create -f nginx.yaml; kubectl apply -f nginx.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromcode
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
